title: SARS2 Wastewater Analysis - BVBRC
subtitle: "Cite the BV-BRC: 10.1093/nar/gkac1003"
intro_text: MultiQC reports summarise analysis results.
report: 
    doi: "10.1093/nar/gkac1003"
show_analysis_paths: False
show_analysis_time: False
custom_logo: bv-brc-header-logo-bg.png
custom_logo_url: https://www.bv-brc.org/
custom_logo_title: Bacterial and Viral Bioinformatics Resource Center
